
import { GoogleGenAI, Type } from "@google/genai";
import type { PlatformContent, Tone, AspectRatio } from '../types';
import { Platform } from '../types';

// IMPORTANT: Do not expose this key publicly.
// It is assumed that process.env.API_KEY is securely handled by the build environment.
const API_KEY = process.env.API_KEY;
if (!API_KEY) {
  throw new Error("API_KEY environment variable not set.");
}
const ai = new GoogleGenAI({ apiKey: API_KEY });

const textModel = 'gemini-2.5-pro';
const imageModel = 'imagen-4.0-generate-001';

const responseSchema = {
  type: Type.ARRAY,
  items: {
    type: Type.OBJECT,
    properties: {
      platform: {
        type: Type.STRING,
        enum: Object.values(Platform),
        description: 'The social media platform.',
      },
      post: {
        type: Type.STRING,
        description: 'The full text content for the social media post, including hashtags for Instagram.',
      },
      imagePrompt: {
        type: Type.STRING,
        description: 'A detailed, creative, and visually descriptive prompt to generate an image that complements the post content.',
      },
    },
    required: ['platform', 'post', 'imagePrompt'],
  },
};

export const generateSocialMediaPosts = async (idea: string, tone: Tone): Promise<PlatformContent[]> => {
  const prompt = `
    You are an expert social media manager. Your task is to generate content for multiple platforms based on a user's idea and a desired tone.

    **Idea:** "${idea}"
    **Tone:** "${tone}"

    **Instructions:**
    1.  Create three distinct posts, one for each of the following platforms: LinkedIn, Twitter, and Instagram.
    2.  **LinkedIn:** Write a professional, long-form post. Use professional language and structure it for readability.
    3.  **Twitter:** Write a short, punchy, and engaging post. Keep it concise and within Twitter's character limits.
    4.  **Instagram:** Write a visually-focused caption. Include relevant and popular hashtags at the end.
    5.  For each post, create a detailed and artistic prompt for an image generation model (like Imagen 4) that visually represents the core message of that specific post. This image prompt should be descriptive and evoke a clear visual.
    6.  Return the output as a JSON array that strictly adheres to the provided schema. Ensure the platform names are exactly "LinkedIn", "Twitter", and "Instagram".
  `;
  
  try {
    const response = await ai.models.generateContent({
      model: textModel,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: responseSchema,
        temperature: 0.8,
      },
    });

    const jsonText = response.text.trim();
    const parsedResponse = JSON.parse(jsonText);
    
    // Ensure the response is an array before returning
    if (!Array.isArray(parsedResponse)) {
      throw new Error("Invalid response format from Gemini API. Expected an array.");
    }

    return parsedResponse as PlatformContent[];
  } catch (error) {
    console.error("Error generating social media posts:", error);
    throw new Error("Failed to generate content from Gemini API. Please check the console for details.");
  }
};

export const generateImage = async (prompt: string, aspectRatio: AspectRatio): Promise<string> => {
  try {
    const response = await ai.models.generateImages({
      model: imageModel,
      prompt: `${prompt}, high quality, photorealistic, vibrant colors`,
      config: {
        numberOfImages: 1,
        aspectRatio: aspectRatio,
        outputMimeType: 'image/jpeg',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating image:", error);
    throw new Error("Failed to generate image from Gemini API. The prompt may have been blocked.");
  }
};
